In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get dimesnions
b.ndim

2

In [9]:
# Get shape
a.shape , b.shape 

((3,), (2, 3))

In [11]:
# Get type
a.dtype

dtype('int32')

In [17]:
# you can specify the data type in the array

a.itemsize , a.size, a.nbytes

new_a = np.array([1,2,3], dtype= 'int16')

new_a.itemsize , new_a.size, new_a.nbytes

(2, 3, 6)

Accessing/Changing specific elements, rows, columns, etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get specific element using the [r,c] notation

print(a[1,5])

13


In [22]:
# Get specific row 

print(a[1,:])

[ 8  9 10 11 12 13 14]


In [23]:
# Get specific column 

print(a[:,2])

[ 3 10]


In [26]:
# Getting a little more fancy [startindex:endindex:stepsize]

print(a[0, 1:6:2])

[2 4 6]


In [29]:
# reassigning values to specific positions in the array

a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [30]:
# 3-d example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# Get specific element (work outside in)
print(b[1,:1,1:])

[[6]]


In [39]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

b[:,1,:] = [[9,9]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


Initializing Different Types of Arrays

In [44]:
# All zeros matrix
np.zeros([2,3], dtype= 'int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
# All ones matrix
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [51]:
# specific numbers matrix
np.full([3,2], [4,5])
np.full([3,2], 5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [54]:
# create an array like another's using different digits
np.full_like(new_a, 4)

array([4, 4, 4], dtype=int16)

In [55]:
# Random decimal digits
np.random.rand(4,2)

array([[0.88109115, 0.05132363],
       [0.47927036, 0.84501635],
       [0.96207877, 0.62147142],
       [0.97335729, 0.31554474]])

In [56]:
# Random decimal digits based on the shape of another array
np.random.sample(a.shape)

array([[0.2498967 , 0.06053708, 0.4026084 , 0.83408127, 0.97851839,
        0.32430038, 0.44827506],
       [0.80423482, 0.74422202, 0.1562779 , 0.4419907 , 0.58928081,
        0.16913274, 0.08123083]])

In [57]:
# Random integer digits
np.random.randint(1,8, size = (3,3))

array([[3, 7, 3],
       [5, 6, 1],
       [3, 6, 3]])

In [58]:
# identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
# repeat arrays on a specific axis
arr = np.array([[1,2,3]]) #notice a list within a list to make the array 2 dimensional
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [66]:
# Creating the matrix in the picture
arr1 = np.ones([5,5], dtype= 'int32')
arr1[1:-1,1:-1] = 0
arr1[2,2] = 9
arr1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [67]:
# course solution
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
# be careful when copying arrays!!!

a = np.array([1,2,3])
b = a.copy() #if we use b = a and change a value in b it will also change it in a when using numpy arrays, therefore we have to explicitly make a copy
b[0] = 100

print(a)

[1 2 3]


Mathematics

In [76]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [77]:
a + 2

array([3, 4, 5, 6])

In [79]:
a += 2 
a

array([3, 4, 5, 6])

In [80]:
a - 2

array([1, 2, 3, 4])

In [81]:
a * 2

array([ 6,  8, 10, 12])

In [86]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [87]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])

a + b

array([2, 2, 4, 4])

In [88]:
a * b

array([1, 0, 3, 0])

In [89]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [90]:
# take the sin of each Value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Linear ALgebra

In [91]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [92]:
# find the determinant
c = np.identity(3)
np.linalg.det(c) 

1.0

In [93]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats, axis=1)

array([1, 4])

In [99]:
np.max(stats, axis=0)

array([4, 5, 6])

In [102]:
np.sum(stats, axis=1)
# axis = 0 moves downwards then looks right, axix 1 moves right the looks downwards

array([ 6, 15])

Reorganizing arrays

In [105]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [110]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1, v2]))
print(np.vstack([v1,v2,v1,v2]))


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [112]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))
print(np.hstack([h1,h2,h2,h1]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.]]


Miscellaneous

In [114]:
filedata = np.genfromtxt('Numpy-FCD-data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [115]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Boolean Masking and Advanced Indexing

In [116]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [117]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [118]:
# Numpy arrays can by indexed using a list
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,6]]

array([2, 4, 7])

In [122]:
# This tells us if any of the values in each column is greater than 50 
np.any(filedata > 50 , axis= 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [120]:
# This tells us if all of the values in each column is greater than 50 
np.all(filedata > 50 , axis= 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [123]:
# Greater than a 100 and less than 50
((filedata > 50 ) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [125]:
# Not Greater than a 100 and less than 50
(~((filedata > 50 ) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])